# Generated by Django 5.1.4 on 2024-12-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskdesc', models.CharField(max_length=255)),  # This should be present
                ('is_completed', models.BooleanField(default=False)),
                ('urgency_rank', models.IntegerField(default=0)),
                ('assigned_to', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('deadline_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
    